### ISSUE TITLE
Table interface and Metadata for meshes

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGeometry/Meshes.jl#132]
I'm not sure if the mesh types are under documented, or this is simply not possible.
How can I attach metadata to mesh vertices and access them via the tables interface?

**Comment by juliohm** [comment]
You are correct that vertex tables are currently not implemented. We have ideas on how to accommodate tables for all k-faces (vertex (k=0), segment (k=1), triangle (k=2), tetrahedron (k=4)). One idea is to store a table for each k. Another idea is to store only the table for the top-face (e.g. triangles) and derive the other tables using Whitney basis and other provably optimal interpolation methods for the user. I think the first idea of storing tables for each k is more flexible, and we could still interpolate for a specific k when the table is not given.

Let me expand on the current design so that you have a more clear picture of what is available and what could be done to accommodate more tables. The main trait for data on meshes is [Meshes.Data](https://github.com/JuliaGeometry/Meshes.jl/blob/7f84b3cf30aedf3a442345edb99f8802aa1719b6/src/traits/data.jl#L5-L27). At the moment it only stores one table for the top-face (a.k.a. element). Any type implementing this trait only needs to implement two methods: `domain` and `values`. The `domain(data)` is the actual geometry+topology of the mesh, the object we run geometric processing algorithm on. The `values(data)` is the table for the top-faces, e.g. triangles in 2D mesh.

Here is an example type implementing the Meshes.Data trait:

```julia
struct MyMeshData{D,T} <: Meshes.Data
  domain::D
  table::T
end

Meshes.domain(data::MyMeshData) = data.domain
Meshes.values(data::MyMeshData) = data.table
```

This is what I do for example in GeoStatsBase.jl where I introduce a particular implementation of the trait called `GeoData`:

```julia
julia> using GeoStats

julia> table = (a=rand(100), b=rand(100))
julia> domain = CartesianGrid(10, 10)

julia> # helper function to construct GeoData
julia> d = georef(table, domain)
100 GeoData{2,Float64}
  variables
    └─a (Float64)
    └─b (Float64)
  domain: 10×10 CartesianGrid{2,Float64}

julia> values(d)
Table with 2 columns and 100 rows:
      a          b
    ┌─────────────────────
 1  │ 0.160061   0.737427
 2  │ 0.878383   0.962248
 3  │ 0.956244   0.253405
 4  │ 0.481447   0.0127361
 5  │ 0.0298061  0.0290216
 6  │ 0.870755   0.942028
 7  │ 0.716712   0.457831
 8  │ 0.883696   0.59684
 9  │ 0.0544122  0.791415
 10 │ 0.138267   0.159311
 11 │ 0.111717   0.545152
 12 │ 0.532353   0.570615
 13 │ 0.719388   0.27278
 14 │ 0.287953   0.208527
 15 │ 0.831476   0.81477
 16 │ 0.251411   0.474964
 17 │ 0.955531   0.205115
 18 │ 0.292039   0.584718
 19 │ 0.214504   0.390701
 20 │ 0.537353   0.611195
 21 │ 0.454623   0.463108
 22 │ 0.0402708  0.308658
 23 │ 0.0784445  0.971731
 24 │ 0.409885   0.180841
 25 │ 0.848193   0.576195
 26 │ 0.945266   0.914212
 27 │ 0.642491   0.227631
 28 │ 0.655855   0.704212
 29 │ 0.719297   0.104386
 30 │ 0.622594   0.478185
 31 │ 0.707541   0.0751767
 32 │ 0.244529   0.0193055
 33 │ 0.12744    0.736038
 34 │ 0.668167   0.0649647
 ⋮  │     ⋮          ⋮

```

A natural extension of the `Meshes.Data` trait could take a parameter `k` in the `values` function to return the table of the vertices instead `values(d, k=0)`.

Let me know what do you think. I can work on this issue over the week to expose a table for the vertices.

**Comment by SimonDanisch** [comment]
I'm not sure if that will solve my use case...
I need a simple way to do:

```julia
m = Mesh(meta(positions, color=rand(RGBA, length(positions)), faces)
m.color
```
And this also then needs to work with all mesh operations like:
```julia
merge(m, m2)
```
Also, its pretty important to store the metadata as array of structs or struct of arrays.
So it should be possible that positions lay like this in memory:

```julia
[pos1x, pos1y, pos1z, color1r, color1g, color1b, color1a, ...]
```
Or 
```julia
pos = [pos1x, pos1x, pos1z, ...]
color = [color1r, color1g, color1b, color1a, ...]
```

**Comment by juliohm** [comment]
>I'm not sure if that will solve my use case...
>I need a simple way to do:
> ```julia
> m = Mesh(meta(positions, color=rand(RGBA, length(positions)), faces)
> m.color
> ```

For illustration purposes, this is how you can achieve a similar result with the current design:

```julia
# please ignore the name georef for now
m = georef(table, SimpleMesh(points, faces))
m[:color]
```

In order to cover your use case, we need to:

1. Add a method to map a table with metadata for points besides the table for triangles. The code snippet above is for metadata on triangles. The way I would proceed here is first introduce a default `Meshes.Data` implementation in Meshes.jl without the `georef` jargon. Then I would create a constructor that takes a mesh and a dictionary of tables `k => tablek` for the metadata.
2. Add a method for getfield so that `getfield(m, col) = m[col]`. This is trivial to add and is already in the plans.

To give you some additional context, we are trying to be extremely careful with metadata to avoid copying it everywhere unintentionally inside geometric processing routines. The current design is assuming that any algorithm that operates on raw geometries without metadata will just call `mesh = domain(m)` to retrieve the raw geometries without copies. After the geometric processing is finished, the metadata can be re-attached with a similar `georef(values(m), processed_m)` call, also without moving memory around.

> And this also then needs to work with all mesh operations like:
> 
> ```julia
> merge(m, m2)
> ```

All operations defined in the package that make sense for both *meshes* and *data on meshes* work like this, but we certainly need to double check if any operation is missing methods.

> Also, its pretty important to store the metadata as array of structs or struct of arrays.
> So it should be possible that positions lay like this in memory:
> 
> ```julia
> [pos1x, pos1y, pos1z, color1r, color1g, color1b, color1a, ...]
> ```
> 
> Or
> 
> ```julia
> pos = [pos1x, pos1x, pos1z, ...]
> color = [color1r, color1g, color1b, color1a, ...]
> ```

That is a very important point. The second option seems more natural and nicer to work with. Here is how I would produce the vector of coordinates:

```julia
julia> using Meshes

julia> m = SimpleMesh(rand(Point2,3), connect.([(1,2,3)]))
1 SimpleMesh{2,Float64}
  3 vertices
    └─Point(0.8119188851982433, 0.953893316177292)
    └─Point(0.7398740838578928, 0.46428819733269666)
    └─Point(0.4346966948083937, 0.8442074945367846)
  1 elements
    └─Triangle(1, 2, 3)

julia> coordinates.(vertices(m))
3-element Vector{StaticArrays.SVector{2, Float64}}:
 [0.8119188851982433, 0.953893316177292]
 [0.7398740838578928, 0.46428819733269666]
 [0.4346966948083937, 0.8442074945367846]
```

For the vector of values, I would just get the column of the metadata table for vertices. Assuming we have it implemented already as `values(data, k=0)`, this is how the conversion could be implemented:

```julia
function to_makie(d::Data, var::Symbol)
  mesh  = domain(d) # the actual mesh
  table = values(d, 0) # metadata for vertices

  # coordinates in the global reference system
  coords = coordinates.(vertices(mesh))

  # values for variable var
  attrib = Tables.getcolumn(table, var)

  coords, attrib
end
```

Would that work with the visualization requirements you have in mind? Is it too expensive to work with the memory layout above? We are open to suggestions. If we could converge on a nice API to work with that is also performant for GPU visualization that would be great.

**Comment by juliohm** [comment]
Another reason why we separated the metadata from the mesh is that many data structures for optimal search in meshes doesn't necessarily store the connectivities explicitly. For example, we have the `HalfEdgeStructure` that only stores half-edges for which metadata doesn't make sense. There is always a mapping from the data structure to the actual faces of rank k, but that is implicit. The StructArrays.jl design works nicely with the `FullStructure` for example because it can be seen as a vector of connectivities where each connectivity has metadata attached.

**Comment by SimonDanisch** [comment]
Yeah, so 90% of the work & design of GeometryBasics went into enabling both memory layouts with as few disadvantages as possible... One could say, that it's the main point of GeometryBasics and it can be very important for the GPU and compat with C libraries ;) It's usually quite difficult to add this to a package in retrospective, so I wonder how that would work in Meshes.

**Comment by juliohm** [comment]
Yes, we also had that in mind in Meshes.jl and the metadata part is still very minimal and open to development. I don't think it will be a problem to change where the metadata is saved in memory because currently it is completely decoupled from the geometries themselves, which is more flexible than a design that couples the two from the start.

Notice that saving metadata next to the geometry is only possible with the `FullStructure` topology common in visualization libraries, and also known as the soup of geometries. All other libraries I know for mesh processing keep the metadata in external arrays, and I think VTK is the most eminent example. VTK is also widely used for visualization.

I will work on the two issues listed above during the week so that we can experiment with the design space that is still open.

**Comment by serenity4** [comment]
As @juliohm pointed out, support for the storage of separate vectors of metadata values can be fairly easy to develop (with one array for positions, one for colors, uv, etc).
For the other memory layout, it can be converted with something like `collect(zip(positions, colors[, other_attributes]))`. I believe the point is that, since metadata is not required for most geometry processing algorithms (ruling out vertex position as metadata), it can always be added externally at the end. Then it's more of a storage matter than a geometry processing one. I get though that such a conversion may be expensive and inefficient to perform, especially with *lots* of vertices.

There was an idea to decouple the combinatorial structure (represented as an abstract polytope) of meshes from its attributes, and considering the position as one type of metadata. Allowing any metadata to be attached to a mesh (including position, but also color/derivatives) would definitely make a performance improvement by avoiding the overhead of an array of structs => struct of arrays conversion and the data duplication in this particular case.

I believe the idea is worth pushing further. For now, you'd have to either use several buffers for your vertex attributes or convert the layout into a array of structs manually.

**Comment by juliohm** [comment]
An update regarding this general representation of meshes.

We are very close from having an intrinsic representation that can be "instantiated" with different types of "vertices": https://github.com/JuliaGeometry/Meshes.jl/blob/c0b11f72e18d90a7c8e71d0ec7f3092909cc6f6a/src/mesh/simplemesh.jl#L5-L23

As you can see in the definition above, our `SimpleMesh` is just a composite type that puts together topology and "vertices":

- The topology is what enables the navigation on the mesh. For example, finding neighboring vertices, adjacent triangles, etc. All these operations, known as topological relations, are defined in the [toporelations.jl](https://github.com/JuliaGeometry/Meshes.jl/blob/master/src/toporelations.jl) file and are implemented for the `HalfEdgeStructure` topology. They cannot be implemented efficiently for the `FullStructure` topology, which is the topology available in GeometryBasics.jl. The `FullStructure` topology is useful for IO and for simple visualizations of the mesh as a "bag of triangles".

- In the most general case, the "vertices" could be considered metadata, but we won't make this generalization yet because it is a bit exotic for the end user, and we need to think carefully about a good design that is also user-friendly. Nevertheless, we are free to pass any vector of "vertices" to materialize the topology with a specific geometry. Currently our vector of vertices is a `Vector{Point{Dim,T}}`.

Next, I will refactor the `Meshes.Data` trait to accommodate metadata tables for all k-faces, including 0-faces (or vertices).

@SimonDanisch do you also need metadata next to geometries in the memory layout or vertex metadata is all that is necessary for efficient visualization? From what I understand, the OpenGL, Vulkan, etc, routines are expressed in terms of vertices with metadata + connecvitivity of triangles.

**Comment by juliohm** [comment]
An update regarding this issue. We should have a working implementation by the end of the day. The implementation will allow the association of metadata to any rank of the mesh. The advantage of this design is that we will be able to load large tables (or databases) lazily from disk, which do not fit into RAM, and still visualize parts of it depending on user interaction.

**Comment by juliohm** [comment]
The feature is now available in the master branch under the name `metadata`. Below is an example of usage where we attach metadata to vertices and elements of a simple mesh:

```julia
julia> vertices = Point2[(0,0),(1,0),(1,1),(0,1)]
4-element Vector{Point2}:
 Point(0.0, 0.0)
 Point(1.0, 0.0)
 Point(1.0, 1.0)
 Point(0.0, 1.0)

julia> elements = connect.([(1,2,3),(3,4,1)])
2-element Vector{Connectivity{Triangle{Dim, T, V} where {Dim, T, V<:AbstractArray{Point{Dim, T}, 1}}, 3}}:
 Triangle(1, 2, 3)
 Triangle(3, 4, 1)

julia> d = metadata(vertices, elements,
         vtable = (temperature=[1.0,2.0,3.0,4.0], pressure=[4.0,3.0,2.0,1.0]),
         etable = (quality=["A","B"], state=[true,false])
       )
2 SpatialData{2,Float64}
  variables (rank 0)
    └─pressure (Float64)
    └─temperature (Float64)
  variables (rank 2)
    └─quality (String)
    └─state (Bool)
  domain: 2 SimpleMesh{2,Float64}
```

As you can see, the function returns a `SpatialData` object, which implements the `Data` trait. In this example, it stores a table for the vertices (rank = 0) and a table for the elements (rank = maximum rank = 2), which happen to be triangles in this example. We can also store tables for any intermediate rank (rank = 1) using the other more general method `metadata(vertices, elements, values)`.

Because it is very common to assign metadata to vertices and elements, I called these two special tables the `vtable` and the `etable`, and introduced special keyword arguments for them as shown above. I think these names are easy to remember, but please let me know if you have other suggestions.

After the object is constructed, we can retrieve any table of interest using the `values` trait function:

```julia
julia> values(d, 0)
(temperature = [1.0, 2.0, 3.0, 4.0], pressure = [4.0, 3.0, 2.0, 1.0])

julia> values(d, 2)
(quality = ["A", "B"], state = Bool[1, 0])
```

Currently, it will return `nothing` for ranks without data, but we can interpolate it in the future using well-known methods for simplicial complexes:

```julia
julia> values(d, 1) == nothing
true
```

As usual, the actual mesh can be retrieved with the `domain` trait function:

```julia
julia> domain(d)
2 SimpleMesh{2,Float64}
  4 vertices
    └─Point(0.0, 0.0)
    └─Point(1.0, 0.0)
    └─Point(1.0, 1.0)
    └─Point(0.0, 1.0)
  2 elements
    └─Triangle(1, 2, 3)
    └─Triangle(3, 4, 1)
```

Please let me know if that addresses your use case @SimonDanisch. My plan is to write tests tomorrow morning, update the documentation, release a new minor version, and update all downstream packages accordingly.

**Comment by SimonDanisch** [comment]
Thank you! 
I think I have to put this on hold though... I hoped Meshes would have taken more of the backbone + features of GeometryBasics, so that it would be easier to switch out, but the APIs, concepts and features are just too different.
I guess we have to go the conversion + recipe route for now ;)

**Comment by juliohm** [comment]
Sounds like a good plan. The recipe route will help identify where to go next.
