### ISSUE TITLE
interoperability with MeshIO.jl

### ISSUE THREAD

**Issue by heliosdrm** [JuliaGeometry/Meshes.jl#139]
Related to https://discourse.julialang.org/t/ann-announcing-meshes-jl/53973/19

It's great that packages like PlyIO provide easy-to-manage arrays and dictionaries, from which `Mesh`es can be easily made, and I agree that it would be good to extend that model to other file formats (OBJ, OFF, etc.). However, regardless of how MeshIO.jl reads/stores data, I would like that Meshes.jl was also able to deal with its output, or save results through it. The reason is that MeshIO is registered in FileIO.jl, so it is a natural interface to load and save mesh files.

This might be supported if `GeometryBasics`, which is the package that provides the types for MeshIO, is added as dependency, and some methods are written to convert between `Meshes.Mesh` and `GeometryBasics.AbstractMesh`. That way, one could just do, for instance:

```julia
using FileIO
load(source_file) |> SimpleMesh
```

(For saving the user should import mesh types from `GeometryBasics`, though)

If that's acceptable I would be willing to contribute

**Comment by juliohm** [comment]
Hi @heliosdrm I think you misunderstood the connection between the different projects. The fix should go in MeshIO.jl not in Meshes.jl We can't add GeometryBasics.jl as a dependency because Meshes.jl is am improved version of GeometryBasics.jl.

MeshIO.jl could be refactored to accommodate Meshes.jl types but that is not part of this repository here.
