### ISSUE TITLE
`length(::Point)` not defined

### ISSUE THREAD

**Issue by visr** [JuliaGeometry/Meshes.jl#140]
Would it be useful to add something like below?
```julia
Base.length(::Point{Dim,T}) where {Dim,T} = Dim
```

Same for `getindex`.

**Comment by juliohm** [comment]
We have the `embeddim` trait that returns the dimension of the space where points and geometries live. A point is an abstract construct that is independent of coordinate reference systems so we can't `getindex` into it. We can however `getindex` into the coordinates of the point in a given CRS. Currently our `coordinates` function simply returns the coordinates used to instantiate the point but the plan is to be able to query different coordinates with respect to different coordinate systems in the future. I think that is what you have in mind too?

We are still brainstorming where the information about the reference system should go. I am considering storing the CRS in each geometry so that whenever we call `vertices(geometry)` the function will take care of converting all coordinates to a common "Euclidean" space. I am still assessing the impact of this design before implementing it. The major benefit would be freeing end users from projections, transformations, etc. They could just load geometries with their own CRS and then Meshes.jl would always converge to a canonical set of coordinates regardless of the individual CRSs of each geometry.

**Comment by visr** [comment]
Ok yeah I was working on https://github.com/JuliaGeo/Proj4.jl/pull/51 and noticed that 

```julia
using Proj4, Meshes
trans = Proj4.Transformation("EPSG:4326", "+proj=utm +zone=32 +datum=WGS84")
trans(Point(1.1, 2.2))
```

Would fail for Meshes, but works for GeometryBasics. I'm aware you don't want a Point to be an AbstractVector, but I thought something like `length` can't really return something else than this definition. Though first taking out the `coordinates` would work as well.

> considering storing the CRS in each geometry

Yeah right now in most places CRS is just an attribute for a whole set of data. QGIS for instance can show different sets together by projecting to the 'project CRS'. I wonder how/if storing it per geometry will be feasible without introducing (too much) extra overhead. Perhaps as a type parameter, but then how to design something that can work both with Geodesy, Proj4 and perhaps other CRS systems you have in mind? Sounds like quite the challenge.

**Comment by juliohm** [comment]
The challenge is finding the right level of granularity. The most flexible design is one in which a CRS is stored per each point but that can quickly become inefficient in terms of storage. Storing the CRS in geometries seems flexible enough and will likely enable features that QGIS doesn't support.

How many CRS exist out there more or less? I will close the issue and open a thread on Zulip to continue this discussion.
