### ISSUE TITLE
Lattice meshes

### ISSUE THREAD

**Issue by mohdibntarek** [JuliaGeometry/Meshes.jl#159]
It would be great to support lattice meshes. For example, a lattice can be a simple mesh or Euclidean grid of elements where each element is of equal size and is actually a mesh itself. All the lattice elements must have the same pattern though.

**Comment by mohdibntarek** [comment]
There are https://github.com/Gregstrq/LightLattices.jl and https://github.com/JuliaPhysics/Lattices.jl which seem active.

**Comment by juliohm** [comment]
Can you elaborate on the differences? I thought that the GridTopology
behind the CartesianGrid is what people usually call lattices in other
fields.

**Comment by mohdibntarek** [comment]
Well lattices have a high level GridTopology but the element can be of arbitrary structure. Think of a GridTopology of turtles.

**Comment by juliohm** [comment]
But how do you think such structures could be useful in the context of
Meshes.jl? Also isn't the GridTopology already agnostic to element types ?

**Comment by mohdibntarek** [comment]
Well GridTopology doesn't care about the nodes or faces inside the element so yes it is element-agnostic in that sense. What I want is something that is a GridTopology of FullTopologies sort of. Then I can iterate over the elements inside a lattice element or inside all the lattice elements.

**Comment by mohdibntarek** [comment]
As for usefullnes, it is useful in a topology optimization setting where I want to optimize the micro-structure of a design/shape. So I optimize the element design and then build a mesh out of this custom element and simulate the physics of the whole structure.

**Comment by mohdibntarek** [comment]
I think a custom element type is probably the way to go.

**Comment by juliohm** [comment]
Yes, I think that is a bit out of scope for Meshes.jl given that it is agnostic to applications. Maybe the lattice concept turns out to be useful in a more general context later on and then we can reconsider adding it here 👍🏽 Given that there are packages with the functionality already available I think you can start combining the concepts in a separate package and then when something is more concrete we see if it makes sense to add here for broader accessibility. Right now we don't have these hierarchical representations sorted out. It is a major next step in the design of the types.
