### ISSUE TITLE
Why Point in Segment restrict in 2d?

### ISSUE THREAD

**Issue by GuoHaoxuan** [JuliaGeometry/Meshes.jl#197]
https://github.com/JuliaGeometry/Meshes.jl/blob/54a9d967fd45faf31bf8146ffa6385b6ad434962/src/polytopes/segment.jl#L37-L43

I think it is method is compatible in 3d. Maybe it is either OK in higher dimension?

**Comment by juliohm** [comment]
I think the cross-product for 3D vectors returns a vector so we would need to update the code accordingly. Could you please confirm @ErickChacon ?

**Comment by ErickChacon** [comment]
Hi @juliohm. Yes, we only need to compare all cross-product elements with zero for the 3d case. I was going to do that, but also I had to start integrating my work with Meshes.jl. For higher-dimensional cases, the code does not work because the cross-product is only defined for 3d (but it is also adapted to 2d). For higher dimensions, I think we need to compute all cross-products for all possible combinations (n 2).

**Comment by ErickChacon** [comment]
I can update the 3d case today, and work on higher dimensions later.

**Comment by juliohm** [comment]
Thank you @ErickChacon 💯
