### ISSUE TITLE
Is there a way to obtain neighbors for each element of a GeometrySet??

### ISSUE THREAD

**Issue by ErickChacon** [JuliaGeometry/Meshes.jl#226]
For some models (mainly in 2d), 1st order neighbors are those elements that share borders (edges). Given a 2d GeometrySet (which is part of a GeoTable), can we obtain the neighbors' indices for each element?

**Comment by juliohm** [comment]
Hi @ErickChacon , a geometry set doesn't store the relationship between the geometries in the set. In order to find these neighbors (e.g. geometries that share boundaries) we need to first convert the geometry set to a different data structure. A similar question was asked in our Zulip channel months ago. It is related to the point location problem: https://en.wikipedia.org/wiki/Point_location
