### ISSUE TITLE
getindex for point

### ISSUE THREAD

**Issue by kylebeggs** [JuliaGeometry/Meshes.jl#284]
Can we add a method for getindex on point types? Like this `Base.getindex(p::Point2, i::Int) = getindex(p.coords,i)`? I find it cumbersome to have to do p.coords[1], p.coords[2] etc... if so I can make a PR

**Comment by juliohm** [comment]
Hi @kylebeggs , we had this issue discussed a few times already. The problem is that the notion of indexing pertains to coordinates in a coordinate system, not to a point, which is an atomic concept. This is by design to force users to be explicit about coordinates, and in the future about coordinate systems explicitly (or implicitly) because the system will be able to handle points in different coordinate systems without getindex everywhere. For example, you can use lat/lon or x/y/z, if your code does getindex(p, 3) it will crash with lat/lon.

**Comment by kylebeggs** [comment]
@juliohm Thanks for explaining. but if I need to access just one coordinate for whatever reason, I still need to do getindex(p.coords,3) anyways which could still make it crash. I suppose your point is we should't be writing code where we might need to access a specific coord in that fashion?

**Comment by juliohm** [comment]
Exactly! Ideally your code should be agnostic to the number of coordinates, and even to the coordinates themselves. Working with coordinates is a more strict way of working in geometry, you can do entire algorithms with abstract points.

But answering your practical question, whenever you need access to the actual coordinates you can use `coordinates(p)` explicitly. In the future, we should be able to say something like `coordinates(p, :LATLON)` or something to specify which coordinates exactly we want for the exact same point.

**Comment by kylebeggs** [comment]
I see. Thanks for taking the time to explain
