### ISSUE TITLE
Violation of Copyright -- Please fix immediately

### ISSUE THREAD

**Issue by yeesian** [JuliaGeometry/Meshes.jl#3]
https://github.com/JuliaGeometry/Meshes.jl/commit/a1d408c64425cd510b60ff5e7eed9a725eae6b6d is in violation of the [MIT license](https://github.com/JuliaGeometry/GeometryBasics.jl/blob/4bc7ebcad7dafae1392ef2fabc3405fcd7c78033/LICENSE) under which the code from https://github.com/JuliaGeometry/GeometryBasics.jl is copied: see accompanying discussion in https://github.com/JuliaGeometry/GeometryBasics.jl/pull/101#issuecomment-711168544.

[Needing to proceed quickly with your own research](https://github.com/JuliaGeometry/GeometryBasics.jl/pull/101#issuecomment-711167660) is not an accepted reason for violating community standards and copyright notices -- please fix this issue immediately.

* To be clear: https://github.com/JuliaGeometry/Meshes.jl/commit/b3907dc4e9e81a3d8520fd688480d76f4c5342ff (c.f. https://github.com/JuliaGeometry/GeometryBasics.jl/pull/101#issuecomment-711169250) is not the right way to fix it.
* Simon and Martjin have agreed that an acceptable way of resolving this issue is to fix the commit history across this repository to reflect that it is a fork of https://github.com/JuliaGeometry/GeometryBasics.jl.
* Failure to do so will result in an escalation of this issue to the Julia Stewards as a violation of https://julialang.org/community/standards/#give_credit.

**Comment by juliohm** [comment]
@yeesian how exactly should this commit history issue be fixed? Is there a set of Git commands that I should run to include the old commits? I had an existing repository with other commits and a branch `cleanup` in GeometryBasics.jl from which I took a subset of the files.

Also, from what I understand from the MIT license, all that one needs to do is to properly copy the license copyright authors forward. So I could just add Martjin to the LICENSE? Would that be a satisfactory solution?

**Comment by yeesian** [comment]
> how exactly should this commit history issue be fixed? Is there a set of Git commands that I should run to include the old commits?

If you veer from accepted norms, the onus is on you to license and release code in a responsible manner. See https://opensource.guide/legal/#what-if-i-want-to-change-the-license-of-my-project and https://opensource.guide/legal/#does-my-project-need-an-additional-contributor-agreement for some of the complications.

> Also, from what I understand from the MIT license, all that one needs to do is to properly copy the license copyright authors forward. So I could just add Martjin to the LICENSE? Would that be a satisfactory solution?

IANAL but https://github.com/salesforce/gorp/pull/3 is one way in which people in a similar situation have resolved it.

**Comment by juliohm** [comment]
I have taken action to fix the issue in all legal scope. No license, including the MIT license, requires copy of commit history. The project GeometryBasics.jl is licensed under MIT, and has always been under this license. The only change that needs to be made is to add all past contributors to the LICENSE file copyright statement as I did.

The list of past contributors can be found with:

```bash
shell> git shortlog -sne --all
    84  Simon <sdanisch@protonmail.com>
    77  zeptodoctor <44736852+zeptodoctor@users.noreply.github.com>
    60  SimonDanisch <sdanisch@protonmail.com>
    52  ARSH SHARMA <184517@nith.ac.in>
    36  Júlio Hoffimann <julio.hoffimann@gmail.com>
    31  SimonDanisch <sdanisch@gmail.com>
    23  Documenter.jl <documenter@juliadocs.github.io>
    18  Simon <sdanisch@gmail.com>
    15  Anshul Singhvi <asinghvi17@simons-rock.edu>
    13  Arsh Sharma <43717431+Sov-trotter@users.noreply.github.com>
    11  Martijn Visser <mgvisser@gmail.com>
     3  Daniel Schwabeneder <daschw@disroot.org>
     2  F Freyer <frederic481994@hotmail.de>
     2  Steve Kelly <kd2cca@gmail.com>
     2  Tim Holy <tim.holy@gmail.com>
     2  mtsch <matijacufar@gmail.com>
     1  Benoît Legat <benoit.legat@gmail.com>
     1  Erik Schnetter <schnetter@gmail.com>
     1  Jan Weidner <jw3126@gmail.com>
     1  Julia TagBot <50554310+JuliaTagBot@users.noreply.github.com>
     1  Mohamed Tarek <mohamed82008@gmail.com>
     1  Paul Jurczak <pauljurczak@yahoo.com>
     1  Zachary P. Christensen <zchristensen7@gmail.com>
     1  ambyld <bylard@stanford.edu>
     1  yha <yharel@campus.technion.ac.il>
```

I've removed the robots from the list (e.g. Julia TagBot and Documenter.jl) and added all the names to the header of the license: https://github.com/JuliaGeometry/Meshes.jl/blob/3a99872cfff2f1cb40ae75fa142a91ef3d0a6741/LICENSE#L1-L4

Additionally, the [ISC](https://en.wikipedia.org/wiki/ISC_license) license in Meshes.jl is *equivalent* to the MIT license, with the only difference being a clearer modern language. Nevertheless, I've changed the license to MIT to avoid any possible doubt about it.

All files in the source code now have a license header, which is the correct way of imposing a license in a project, something that GeometryBasics.jl does not do by the way, and that I do in all my projects, see JuliaEarth.

Now that the issue is fixed legally, I want to point out that you don't have the rights to accuse people of something legal when you are not a lawyer. You threatening me saying that this will be escalated to the Julia Stewards in case I don't complain to someone else's desires (which aren't based on law) is unnecessary. Next time you pick a battle for someone else, even if it is with good intention, please make sure you choose the appropriate tone before accusations of illegal work. I am an active member of the Julia community and never had any intention to infringe law.

If you feel that something still needs to be fixed legally, please reopen the issue.
