### ISSUE TITLE
Precision of segment intersection

### ISSUE THREAD

**Issue by henry2004y** [JuliaGeometry/Meshes.jl#320]
The following code shows difference between version 0.24 and 0.25:

```julia
seg1 = Segment(Point(2.0, 2.0), Point(3.0, 1.0))
seg2 = Segment(Point(2.125005,1.875003), Point(50000.0,30000.0))
seg3 = Segment(Point(2.125005,1.875003), Point(50002.125005,30001.875003))
# Meshes v0.24
seg1 ∩ seg2 #Nothing
seg1 ∩ seg3 #Nothing
# Meshes v0.25
seg1 ∩ seg2 #Nothing
seg1 ∩ seg3 #Point(2.125005, 1.875003)
```

Analytically, `Point(2.125, 1.875)` lies exactly along `seg1`, so Meshes v0.24 gives the correct result `Nothing`. This seems to be related to precisions of floating numbers?

**Comment by juliohm** [comment]
@dorn-gerhard as you can see that PR we merged is quite delicate. Can you please take a look at this? It would be great if we could provide a hotfix.

**Comment by juliohm** [comment]
Thank you @henry2004y for opening the issue. Please let us know if you have a fix, feel free to submit a PR as well.

**Comment by dorn-gerhard** [comment]
the reason is that we currently use the relative parameter `λ` of a segment which is between zero and one and so indicates intersections relative to the length of a segment.
the intersection of seg1 and seg3 seen from seg3 is `λ = -9.999999999732445e-11` which is rounded according to the tolerance of Float64 (`atol(Float64) -> 10^-10`)

(Use `Meshes.intersectparameters(seg1(0), seg1(1), seg3(0), seg3(1)) to see the resulting parameters)

We can fix that by using the length of Segments (the defining points of Lines and Rays).
and use for instance
``` julia 
a, b = s1(0), s1(1/length(s1))
c, d = s2(0), s2(1/length(s2))
```
then the resulting parameters will have an actual length scale.

Please give feedback. 
Based on your thoughts, I can prepare a PR (changes are needed in: `rays.jl, lines.jl, segments.jl, raylines.jl, raysegment.jl`)

**Comment by juliohm** [comment]
I remember having to use a squared tolerance somewhere in the old code to avoid these rounding issues because the old algorithm was computing areas. If tol is the tolerance for lengths, then tol^2 is the tolerance for areas.

@dorn-gerhard, if you know a good fix for the new algorithm already, feel free to start a PR. I am happy to review it.

**Comment by dorn-gerhard** [comment]
PR #321 should solve the problem

**Comment by juliohm** [comment]
Fixed on master. We are in the process of releasing a new minor release with a set of breaking improvements to the interface.
