### ISSUE TITLE
merge duplicated vertices

### ISSUE THREAD

**Issue by stla** [JuliaGeometry/Meshes.jl#338]
Hello, 

[Here](https://gist.github.com/stla/8519c06e7f557bd8381dc03ca22068d9) is a function which merges the duplicated vertices in a triangle mesh, and renumbers the triangles accordingly.

**Comment by juliohm** [comment]
@stla please open pull requests if you would like to see these functions added.

**Comment by stla** [comment]
Ok, but before opening a PR I wanted to know whether you're interested for example?

**Comment by juliohm** [comment]
We have different layers of discussion to narrow down issues. First, it is usually a good idea to chat informally on our community channel:

https://github.com/JuliaGeometry/Meshes.jl#contributing

This issue here fits into this category where you are simply sharing a snippet of code asking if it is of interest.

Then, we can nail down what exactly are the concepts and ideas that are general enough to be ported to the package. For example, the concept of a Torus as a primitive would be welcome.

Finally, we open an issue to track the feature request, and start working on the pull request.
