### ISSUE TITLE
Improve rotation standards

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#344]
We have a couple of issues with vanilla ReferenceFrameRotations.jl rotation objects:

1. They describe rotations of frames and we always need to flip signs of angles to flip geometries and meshes
2. They are defined for 3D embeddings only, and we had to introduce our own 2D rotations in [src/rotations.jl](https://github.com/JuliaGeometry/Meshes.jl/blob/1432107f191130f3fe3792b00816b4057b236a51/src/rotations.jl)

I am opening this issue to discuss a general improvement regarding our rotation interface to facilitate the lives of end-users who are mostly interested in rotating geometries and meshes, not frames.

As a starting proposal I suggest that we introduce a new set of rotations in `src/rotations.jl` to flip the signs of angles in existing rotation types from ReferenceFrameRotations.jl. For example:

```julia
IEulerAngleAxis(angle, axis) = EulerAngleAxis(-angle, axis)
```

We can export this list of standardized "inverse" rotations and drop support for vanilla rotation types from ReferenceFrameRotations.jl. This doesn't mean that we will stop using ReferenceFrameRotations.jl, it just means that end-users will only interface with the features of the package via a set of well-defined geometry-oriented rotation types as opposed to frame-oriented rotation types.

@ronisbr in case you have a suggestion for an alternative solution that involves changes to ReferenceFrameRotations.jl itself, please let us know. These angle signs are very error-prone and our users are not usually thinking in terms of frames. If you feel that these `IRotation` types should live in ReferenceFrameRotations.jl, we can work on a PR over there.

cc: @stla

**Comment by ronisbr** [comment]
Hi @juliohm !

I think the problem is that you want to rotate vectors, whereas ReferenceFrameRotations.jl rotates reference frames. It is what we call active and passive rotations. Those are different exactly by that inverse signal.

https://en.wikipedia.org/wiki/Active_and_passive_transformation

Are you sure you want here to rotate the reference frame instead of rotating vectors in the same reference frame?

**Comment by juliohm** [comment]
Hi Ronan! We want to rotate vectors mostly. That is why we need other
rotation types that differ from the ones in ReferenceFrameRotations.jl

Em qua., 21 de dez. de 2022 12:44, Ronan Arraes Jardim Chagas <
***@***.***> escreveu:

**Comment by ronisbr** [comment]
Hum, so every rotation will be inverted. I have no idea what is the best way to fix this. In Julia, we have Rotations.jl that has active rotations, and ReferenceFrameRotations.jl that has passive rotations but follows an approach closer to MATLAB.

**Comment by juliohm** [comment]
@ronisbr wouldn't it be enough to create new "constructors" that flip the signs of angles? It is more complicated than that I guess because some rotations are defined in sequence with multiple axes right? Is there a formal bridge between active and passive rotation systems? Something that could be implemented in ReferenceFrameRotations.jl?

**Comment by juliohm** [comment]
It seems that Rotations.jl has copied a lot of ReferenceFrameRotations.jl in the latest version. The last time I looked into it, it was quite primitive. Now it has similar types for EulerAngles, DCM, etc. Maybe we should reassess the package as a dependency here.

Ideally, we would have a single package dealing with both active and passive rotations, but I don't know how hard this is to implement.

**Comment by ronisbr** [comment]
> Something that could be implemented in ReferenceFrameRotations.jl?

The problem here is that a reference frame rotation is always passive, by definition. Hence, I think it will not be good to add some kind of treatment to change the rotation to active inside this package.

Let me think about it for a while :)

**Comment by juliohm** [comment]
Perhaps a new package that combines the approaches in ReferenceFrameRotations.jl and Rotations.jl and solves the problem once and for all?

**Comment by ronisbr** [comment]
Both APIs are very different. I am thinking in a conversion layer for ReferenceFrameRotations that modifies everything (including operations) to active.

**Comment by hyrodium** [comment]
>It seems that Rotations.jl has copied a lot of ReferenceFrameRotations.jl in the latest version.

Is it true? I am a developer of [Rotations.jl](https://github.com/JuliaGeometry/Rotations.jl), and I do think we have not copied code from ReferenceFrameRotations.jl.

>The last time I looked into it, it was quite primitive. Now it has similar types for EulerAngles, DCM, etc.

`Rotations.RotXYZ` (EulerAngles) and `Rotations.RotMatrix` (DCM) have existed since at least [Rotations.jl v0.3.4](https://github.com/JuliaGeometry/Rotations.jl/tree/v0.3.4) which was released on 2017-01-24 (before Julia v0.6.0!).

**Comment by juliohm** [comment]
I don't know if the appropriate word is "copying", I just meant that all these variants (EulerAngles, and other constructors) were not there the last time I looked into Rotations.jl (at least I don't remember).

The discussion here is an attempt to merge these two separate efforts, which exist for historical reasons as I understand it. I am positive that the community would benefit from seamless conversion between active and passive rotation systems.

**Comment by ronisbr** [comment]
Hi @juliohm !

I just had an amazing idea!

The only moment you need to decide whether a rotation is active or passive is when creating one. All the other operations (composing, inversion, vector rotation, etc.) does not change. So, I propose the following approach:

Add a function called `active_rotation`, where you can convert any rotation supported by ReferenceFrameRotations.jl to active. Hence, you can do: `angle_to_dcm(pi, pi/2, pi/3, :XYZ) |> active_rotation`.

Do you think this will solve your problem? It is very easy to implement.

**Comment by juliohm** [comment]
Hi @ronisbr ! 

That would certainly help 👍🏽 Maybe a simple function name like `switch_rotation_system` to perform this conversion? I understand that this function can be applied twice to get back the original passive system? It is just a matter of flipping signs of angles, right?

It would be super nice if we could configure this system globally with something like `set_rotation_system!(:active)` in our `__init__`

**Comment by juliohm** [comment]
I also wonder if it would make sense to migrate all the code to the shorter module name Rotations.jl. If the maintainers of both packages could work together on this repo moving forward that would be ideal, but I understand if that is not possible.

**Comment by hyrodium** [comment]
I agree that it would be nice to have compatibility between these two rotation packages. I will start by looking into ReferenceFrameRotations.

**Comment by ronisbr** [comment]
Hi @juliohm !

> That would certainly help 👍🏽 Maybe a simple function name like switch_rotation_system to perform this conversion? I understand that this function can be applied twice to get back the original passive system? It is just a matter of flipping signs of angles, right?

I think not. Is there really a use-case for converting to and from active and passive rotations during the execution? I mean, when you create a rotation, or you want to rotate vectors or you want to rotate reference frames. I have never seen an application that requires to change the interpretation. Hence, something like this will add unnecessary complications.

Notice that I will not change any type in ReferenceFrameRotations.jl, I will just add a function to allow creating active rotations easily.

> It would be super nice if we could configure this system globally with something like set_rotation_system!(:active) in our __init__

This feature is also very dangerous. There is no meaning to define a rotation matrix as passive or active since it only depends on your interpretation. All the operations are the same, your interpretation that changes. The only difference is when you are creating a rotation entity. That's why I think the wrapper `active_rotation` is the way to go.

> I also wonder if it would make sense to migrate all the code to the shorter module name Rotations.jl. If the maintainers of both packages could work together on this repo moving forward that would be ideal, but I understand if that is not possible.

Yes! This would be ideal. However, we may face problems given the applications we have related to ReferenceFrameRotations.jl. See https://github.com/JuliaSpace/ReferenceFrameRotations.jl/issues/25#issuecomment-1385450293 for example.

**Comment by ronisbr** [comment]
> I agree that it would be nice to have compatibility between these two rotation packages. I will start by looking into ReferenceFrameRotations.

Good! Another important point is that I select the API in ReferenceFrameRotations. was selected to be somewhat close to what we have in the MATLAB's aerospace toolbox with some improvements (like changing `angle2dcm` to `angle_to_dcm`).

**Comment by juliohm** [comment]
> I think not. Is there really a use-case for converting to and from active and passive rotations during the execution? I mean, when you create a rotation, or you want to rotate vectors or you want to rotate reference frames. I have never seen an application that requires to change the interpretation. Hence, something like this will add unnecessary complications.

I think the use-case is more about setting a convention at some specific place once (e.g. `__init__`) and then using that convention consistently throughout the ecosystem of interest. Right now, the community of users interested in rotations is split between Rotations.jl and ReferenceFrameRotations.jl for no strong reason.

> This feature is also very dangerous. There is no meaning to define a rotation matrix as passive or active since it only depends on your interpretation. All the operations are the same, your interpretation that changes.

Can you clarify the danger here? Why is it dangerous to be explicit about the interpretation?

> Yes! This would be ideal. However, we may face problems given the applications we have related to ReferenceFrameRotations.jl.

Still don't get it why a generalization of the code would be a problem to any application. We are not removing functionality with the discussion in place, but generalizing it so that both user communities get what they want easily. I may be missing something though.

**Comment by ronisbr** [comment]
> I think the use-case is more about setting a convention at some specific place once (e.g. __init__) and then using that convention consistently throughout the ecosystem of interest. Right now, the community of users interested in rotations is split between Rotations.jl and ReferenceFrameRotations.jl for no strong reason.

Yes, but notice that the package is named `ReferenceFrameRotations`, it is supposed to by passive. Since there is no way to "mark" a rotation as active or passive, this separation can avoid many errors. MathWorks took the same approach in the Aerospace Toolbox. It has its own rotation system that is 100% passive.

IMHO, the best approach is a general package that wraps the existing functionality and provides this kind of abstraction you want.

> Can you clarify the danger here? Why is it dangerous to be explicit about the interpretation?

Let's say someone adds `set_rotation_system!(:active)` in `startup.jl` or somewhere else. Everything will be wrong without any warning or noticeable side effect. I am really against any type of global configuration since it can lead to very strange problems.

> Still don't get it why a generalization of the code would be a problem to any application. We are not removing functionality with the discussion in place, but generalizing it so that both user communities get what they want easily. I may be missing something though.

Generalizing is not the problem, it is very welcome! The problem is if this generalization requires breaking modifications in ReferenceFrameRotations.jl.

**Comment by ronisbr** [comment]
Just had an idea: Why not creating a package called `AbstractRotations.jl` that wraps ReferenceFrameRotations.jl and Rotations.jl giving the functionality @juliohm wants?

**Comment by juliohm** [comment]
I think having a playground to design a new set of functions that accommodates both active and passive rotations is beneficial. You could brainstorm the requirements together and then when things converge to a general interface, you could decide what to do with the current packages.

My impression is that there is some design space to be explored that detaches from historical works by MathWorks.

**Comment by hyrodium** [comment]
I'm not much familiar with the inside of Meshes.jl, but is there any problem with replacing ReferenceFrameRotations.jl with Rotations.jl? Rotations.jl supports:

* Active rotations
* Various types of rotation such as [Euler angles](https://juliageometry.github.io/Rotations.jl/stable/3d_euler/), [quaternion](https://juliageometry.github.io/Rotations.jl/stable/3d_quaternion/), [DCM](https://juliageometry.github.io/Rotations.jl/stable/3d_matrix/), etc.
* [2D rotations](https://juliageometry.github.io/Rotations.jl/stable/2d_matrix/) (and [some methods for higher dimensional rotation](https://juliageometry.github.io/Rotations.jl/dev/general_dimensional_rotations/))

I am just not sure what features of ReferenceFrameRotations.jl that Meshes.jl requires that are not supported by Rotations.jl.

**Comment by juliohm** [comment]
That is a possible way forward, but I am interested in understanding why we
need to split the user base just because of a sign convention.

Em qua., 18 de jan. de 2023 14:37, Yuto Horikawa ***@***.***>
escreveu:

**Comment by ronisbr** [comment]
> That is a possible way forward, but I am interested in understanding why we
need to split the user base just because of a sign convention.

Just an important notice: it is not a minor sign convention! It changes everything. There was at least one satellite that failed due to this exactly problem.

In attitude control, the biggest issue is that the problem stays dormant until it flies since you normally cannot reproduce the dynamics on the ground. Hence, as MathWorks decided, I think the best way is to provide different packages for vector rotations and reference frame rotations (active and passive). What we can improve is creating a new package to make it easier to switch between the two.

Maybe if we were developing from start, the best would be to have a package with just the mathematical operations (which are equal except for the derivatives), and then two packages: ReferenceFrameRotations and VectorRotations that uses the same background but with different initialization functions.

**Comment by juliohm** [comment]
@hyrodium I took a look into Rotations.jl again and it seems that you did a very good job refactoring the code and cleaning it up. I am considering replacing ReferenceFrameRotations.jl by Rotations.jl as you suggested given that we are mostly interested in active rotations.

Do you think that you could submit a PR here with the necessary changes? Also, do you think you could drop the dependency on Statistics given that it is only imported for the `mean` function? It should be enough to replace mean by sum / length. What about the dependency on Quaternions.jl? Should this module be copied/pasted directly inside Rotations.jl so that we don't loose track of dependencies in the future?

**Comment by hyrodium** [comment]
@juliohm
Thank you for the comment! I will take a look into Meshes.jl on this weekend and create a PR for that.

>Also, do you think you could drop the dependency on Statistics given that it is only imported for the `mean` function?

Thanks for the suggestion. I opened a PR to remove the dependency on Statistics.jl (https://github.com/JuliaGeometry/Rotations.jl/pull/255).

>What about the dependency on Quaternions.jl? Should this module be copied/pasted directly inside Rotations.jl so that we don't loose track of dependencies in the future?

I believe we should keep the dependency on Quaternions.jl. I'm also maintaining Quaternions.jl. See https://discourse.julialang.org/t/ann-quaternions-jl-v0-7-0/91368 for more information.

**Comment by juliohm** [comment]
Thank you @hyrodium , I think it makes sense to preserve Quaternions.jl as a dependency as you suggested. I understand it has a more general scope than just rotations, and can be useful to other people.

**Comment by juliohm** [comment]
@hyrodium any update on this?

**Comment by hyrodium** [comment]
Sorry for being late. I took a look into the code two weeks ago, but I couldn't have time to implement that. I will try to make a PR in a week💪
