### ISSUE TITLE
Performance problem when creating HalfEdgeTopology on 0.27.0+

### ISSUE THREAD

**Issue by felipeek** [JuliaGeometry/Meshes.jl#380]
Hello, it looks like the `adjsort` loop (added in this PR: https://github.com/JuliaGeometry/Meshes.jl/pull/355) introduced a performance issue when creating the `HalfEdgeTopology` of a mesh.

For example, in 0.26.6 the standorf bunny takes:

```
@time HalfEdgeTopology(mesh.topology.connec)
0.134452 seconds (347.70 k allocations: 94.465 MiB)
```

whereas in 0.27.0 it takes:

```
@time HalfEdgeTopology(mesh.topology.connec)
7.229574 seconds (10.82 M allocations: 1.509 GiB, 2.32% gc time)
```

In my case I am working with meshes that have more than 200k vertices, so the time becomes way larger, which impedes me to move to 0.27.0+

**Comment by juliohm** [comment]
Thank you for reporting the performance issue @felipeek. Do you have a suggestion to improve the situation? Maybe we should add an option to the HalfEdgeTopology to skip the adjsort step when the input mesh already has consistent orientation?

Feel free to suggest an improvement. If you can submit a PR that is even better.

**Comment by juliohm** [comment]
@felipeek I've added an option `sort=true` to the constructor of HalfEdgeTopology so that you can disable the sorting operation. This option will be enabled by default for correctness because many meshes in the wild come with inconsistent orientation of elements. Let me know if that something else doesn't work.
