### ISSUE TITLE
Angle definitions

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#409]
Moving the discussion from Zulip, where we want to address a few issues regarding our current angle implementations:

1. Improving the numerical robustness of the implementation.
2. Defining the open/closed ends of the interval in which angles are returned
3. Defining how signed & unsigned angles are handled in dimensions higher than 2

cc: @mfsch, @JeffreySarnoff

**Comment by mfsch** [comment]
Regarding 2: I think for angles that disregard orientation, the range [0, π] is the only real option. For oriented angles, the unsigned range [0, 2π) is the natural choice and I think it makes sense to have extra checks that exclude the upper boundary 2π in favor of 0, perhaps even within a certain tolerance (e.g. with `isapprox`). In #396, @JeffreySarnoff mentioned that this implies that signed angles should therefore be in [−π, π), i.e. also closed at the lower end, to avoid issues when mapping one range to the other. I’m not sure if that’s the case, since it seems to me that the only difference is whether you use `<` or `<=` in the conditional when converting one to the other, but perhaps I’m overlooking something? Otherwise, I think the range (−π, π] feels more natural to me and I think that’s the one I would expect without reading the documentation. In my view, the open questions therefore are (a) whether the signed interval should be closed at the lower or higher end, and (b) whether the open end of the interval should be handled with `==` or `isapprox`.

**Comment by mfsch** [comment]
@juliohm, did you ever make a decision more generally about you want to approach floating-point precision more generally within Meshes.jl? I’ve noticed that `Point(0.1 + 0.2) ∈ Segment((0.0,), (0.3,))` gives `false`, so it seems that in that case at least you have zero tolerance for floating-point errors. The rasterization algorithm I implemented constructs a number of prism shapes and loops over points in each of those prisms, so it only works if no points can “fall in the gap” between two prisms due to floating-point errors. I therefore have a tolerance argument in the “point-in-prism” check I implemented.

**Comment by juliohm** [comment]
@mfsch I think we can move this discussion about tolerance to Zulip to keep the issue focused on angles. But answering your question, we try to use isapprox always in the current codebase. If some algorithm is using isequal or == we need to fix. At some point in the future we may consider interval arithmetic, but we are moving one step at a time.

**Comment by juliohm** [comment]
Our angle definitions seem to work well in most algorithms implemented here, and there are quite a lot of them. I will close this issue given that there is no urgent demand to rethink the angle ranges. The main update in the master branch is that angles are unitful quantities now, to remove any ambiguity between radian and degree angles.
