### ISSUE TITLE
Stack overflow for discretize(Box{3})

### ISSUE THREAD

**Issue by chrstphrbrns** [JuliaGeometry/Meshes.jl#478]
```julia
julia> discretize(Box((0,0),(1,1)))
2 SimpleMesh{2,Float64}
  4 vertices
    └─Point(0.0, 0.0)
    └─Point(1.0, 0.0)
    └─Point(1.0, 1.0)
    └─Point(0.0, 1.0)
  2 elements
    └─Triangle(1, 2, 3)
    └─Triangle(1, 3, 4)

julia> discretize(Box((0,0,0),(1,1,1)))
ERROR: StackOverflowError:
Stacktrace:
     [1] simplexify(geometry::Box{3, Float64})
       @ Meshes ~/.julia/packages/Meshes/OdYMO/src/discretization.jl:126
     [2] discretize(geometry::Box{3, Float64})
       @ Meshes ~/.julia/packages/Meshes/OdYMO/src/discretization.jl:99
--- the last 2 lines are repeated 39990 more times ---
 [79983] simplexify(geometry::Box{3, Float64})
       @ Meshes ~/.julia/packages/Meshes/OdYMO/src/discretization.jl:126
```

**Comment by juliohm** [comment]
Thank you for reporting the issue @chrstphrbrns.

First we need to copy/paste the method we define for Hexahedron to Box here:

https://github.com/JuliaGeometry/Meshes.jl/blob/173f7ef43e61d2b795471402f293e43467096d84/src/discretization/tetra.jl#L12-L15

Second, we need to define the `simplexify` method for `Box{3}` here:

https://github.com/JuliaGeometry/Meshes.jl/blob/173f7ef43e61d2b795471402f293e43467096d84/src/discretization.jl#L146

Third, we need to add tests to merge the changes and release a fix.

Would you like to give it a try? This issue is very easy to fix.
