### ISSUE TITLE
Warning related to SimpleTraits.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#53]
Do you know what is happening here? How to fix this warning during precompilation?

```julia
julia> using Meshes
[ Info: Precompiling Meshes [eacbb407-ea5a-433e-ab97-5258b1ca43fa]
WARNING: Method definition _linear(D, Any) where {D} in module Meshes at /home/juliohm/.julia/packages/SimpleTraits/1wYi7/src/SimpleTraits.jl:331 overwritten on the same line (check for duplicate calls to `include`).
  ** incremental compilation may be fatally broken for this module **
```

**Comment by serenity4** [comment]
I've never used SimpleTraits, but it looks like the dispatching bit `IsGrid{D}` is ignored or something (judging by the warning message). It's very strange though, because the _linear trait function you defined (snippet below taken from Meshes) matches the documented example very well.
```
@traitfn _linear(domain::D, inds) where {D; IsGrid{D}} =
  vec(LinearIndices(size(domain))[inds])
@traitfn _linear(::D, inds) where {D; !IsGrid{D}} = inds
```
It's a bit different from mauro3/SimpleTraits.jl#7, but maybe related?

**Comment by juliohm** [comment]
I think it is the exact same issue. I asked there to see if he has a good fix in mind.

**Comment by lassepe** [comment]
I am also seeing this warning. However, it seems to happen non-deterministically; or at least it may depend on the include order?
