### ISSUE TITLE
intersection/clipping not working properly in the 2D case

### ISSUE THREAD

**Issue by CNOT** [JuliaGeometry/Meshes.jl#790]
I reported this earlier in  issue #728 , however as it seems to be a distinct problem I'm opening a new issue for it. Here's a MWE showing the problem:

```julia
using Meshes
using CairoMakie
cg = Meshes.CartesianGrid((0.0, 0.0), (2.0, 1.0), (0.1, 0.1))
ps = Meshes.Point2[(0.0, 0.0), (1.0, 0.5), (1.0, 1.0), (2.0, 0.0)]
pol = Meshes.PolyArea(ps)
viz(pol,showfacets = true)
for i in faces(cg, 2)
    cl = i ∩ pol # Same thing happens with clip(i,pol, SutherlandHodgman())
    if cl != nothing
        viz!(i,showfacets = true, alpha = 0.5, facetcolor = :red)
    end
end
Makie.current_figure()
```

![mwe](https://github.com/JuliaGeometry/Meshes.jl/assets/7808287/2c7403cf-5e6f-41e0-9fcf-33b73dc0a415)

**Comment by juliohm** [comment]
The issue was fixed, and a patch release is on its way:

![image](https://github.com/JuliaGeometry/Meshes.jl/assets/3345261/e3fd641f-fe32-47c0-ba93-381fe49f8dfc)

The Sutherland-Hodgman algorithm assumes a convex clipping geometry. We have to flip the order of arguments when the clipping geometry is not convex. A more performant and general solution requires an alternative clipping algorithm (e.g. Weiler-Atherton) as discussed in #578

**Comment by CNOT** [comment]
Great! Is there an expected timeline for the preferred clipping algorithms?

**Comment by juliohm** [comment]
We are busy working on the new coordinate system infrastructure. No
deadlines for clipping. Contributions are welcome.

Em seg., 4 de mar. de 2024 16:36, Ali Hamed Moosavian <
***@***.***> escreveu:
