### ISSUE TITLE
Stack overflow error in `intersection(Plane, CartesianGrid)`

### ISSUE THREAD

**Issue by DylanMMarques** [JuliaGeometry/Meshes.jl#836]
Hello,

There is a stack overflow error when intersecting a `Plane` with a `CartesianGrid`:
```julia
a = CartesianGrid((10,10,10))
b = Plane(Point(1.0,2.0,1), Vec(0.0,0.0,1.0))
intersection(b,a)
```
```julia
ERROR: StackOverflowError: 
Stacktrace:
     [1] intersection(f::Function, g₁::CartesianGrid{3, Float64}, g₂::Plane{Float64})
       @ Meshes ~/.julia/packages/Meshes/5T0qz/src/intersections.jl:100--- the last 1 lines are repeated 79982 more times ---
```

Thanks

**Comment by juliohm** [comment]
This method is not defined. Please check the methods defined in the
intersections.jl file and tests.

Em ter., 23 de abr. de 2024, 08:15, Dylan Marques ***@***.***>
escreveu:

**Comment by juliohm** [comment]
Whenever a method is missing, the intersection function calls itself with the arguments swapped, to exploit the symmetry. The intersection of a Plane and a CartesianGrid can be many things, and we will likely not implement it here as a method of `intersection`.

**Comment by mikeingold** [comment]
@juliohm I’m not at my computer at the moment but if I remember correctly this kind of error occurs because we define a fallback method something like `f(a,b) = f(b,a)` and, in the event that neither method has been implemented, this results in an infinite recursive loop that overflows the stack. What if we tweaked this method to something like:

```julia
f(a, b) = hasmethod(f, typeof.(b, a)) ? f(b, a) : error()
```

This would at least return an informative error that doesn’t look so much like a bug.

**Comment by juliohm** [comment]
That is a good idea @mikeingold , I wonder if this `hasmethod` call has any impact on performance. Probably not. Will investigate it when I find some time 👍🏽

**Comment by juliohm** [comment]
@mikeingold the idea doesn't seem to work because we have a catch-all method. `hasmethod` always returns true. If you have another solution/suggestion, please feel free to share.
