### ISSUE TITLE
Separate parametric from non-parametric primitives?

### ISSUE THREAD

**Issue by stillyslalom** [JuliaGeometry/Meshes.jl#89]
It seems strange for `Chain` and `Segment` to be `<: Polytope` while `BezierCurve <: Primitive`. Do we want to separate these 'parametric primitives' into their own category?

**Comment by juliohm** [comment]
@stillyslalom the only reason we add a common parent type is if we foresee a common set of applications where dispatching on the abstract type would simplify things. If you read the docstring of `Primitive` you will see that it is for geometries that have a somewhat analytical form. They are not discretizations or junctions of smaller flat parts as a `Polytope`.

So answering your question, I don't think we have a good reason to mix these two parent types here. @serenity4 do you agree?

**Comment by juliohm** [comment]
Think of `Polytopes` as as the natural building blocks of a polygonal mesh. There are other representation of surfaces with Bezier that would benefit from the `BezierCurve` type but these representations are so orthogonal that we don't want to mix the types. That is my current opinion, but it may change in the future.

**Comment by serenity4** [comment]
To be accurate, polytopes (abstract polytopes at least but that's the formalism we use) only describe combinatorial information with some kind of hierarchical inclusion. It doesn't even assume that the result will be polygonal. So, a lot of geometrical objects are polytopes (see a digon for example, it's curved). A bezier curve is actually not a polytope, since the vertices it uses are not all necessarily contained in the final curve (except endpoints); though its associated control polygon is (and is actually a `Chain` semantically).

**Comment by juliohm** [comment]
Nice. I think we can close this issue and if something else pops up in the future we can reconsider a change in the hierarchy of types. So far we don't have a good reason to refactor the type hierarchy. 👍🏽

**Comment by serenity4** [comment]
Whether an object is a primitive or a polytope is independent of the other. Primitive objects are "simple" objects, though it's a bit blurry what is a primitive or not. It is what may compose more complex geometries. So, mixing them would not make sense, I agree with that. Though some geometries are both. If we need to dispatch on both for the same type, we may consider using traits.
