### ISSUE TITLE
Segment can be constructed from more than 2 points?

### ISSUE THREAD

**Issue by lassepe** [JuliaGeometry/Meshes.jl#92]
To my surprise the following does not error:

```julia
using Meshes: Segment

Segment((0, 0), (0, 1), (0, 2))
```

Is this intended?

**Comment by juliohm** [comment]
Please ask questions in our Zulip channel if possible. The link is in the README. I think you need a `Chain` of points instead of a single line `Segment`.

**Comment by juliohm** [comment]
Yes, this is an issue we discussed before on Zulip. We could in theory check the lenght of the input vector and thrown an error, but that is an expensive check in general. If your are using the Segment with `Segment(a, b)` that is fine because it creates a static vector under the hood. But in some cases (meshes) we just take a view from a global vector of points and so the internal vector becomes a vector of uknown length at compile time. We decided that this check was bad for performance reasons. We assume that users won't try to create segments that are conceptually incorrct (according to the doc string).

**Comment by serenity4** [comment]
I think we really should investigate the impact of potential checks. I think the overhead may be close to nothing (just like when we check for the input range when evaluating parametric types). The less assumptions on the user side, the less likely users will have bugs. I think we should avoid silent bugs claiming that it's the user responsibility when it happens wherever possible, particularly if there is no actual performance cost in checking user input.
From quick local tests adding a check is optimized away for static arrays (since the size is known to the compiler). There might be a small performance difference for plain vectors (well, it adds a length computation and a boolean check), but if one wishes performance he should use static arrays directly IMO.

**Comment by juliohm** [comment]
> if one wishes performance he should use static arrays directly IMO.

I think the problem is that the user doesn't have control of this. When we are taking views of the global vector of points in a unstructured mesh, these views won't be static.

Another alternative would be to add checks that are deactivated with a macro. Something like a global variable or environment variable that forces a fast version of things without safety checks. Similar to an `@assertion` but with guarantees that the chunk of code will be completely removed if needed.

I just think that adding these checks everywhere can really make the code ugly to read. So if we feel that this will improve the experience at the end of the day, we can consider it. I just wonder why people consistently try to construct `Segment` with more than 2 points...

**Comment by juliohm** [comment]
In other words, if people are using a `Segment` in a GIS context where they care about staticness of a few segments, then it is fine to use the constructor that leads to an internal static vector. Maybe in this case the check makes sense, just for a particular constructor. If, however, people are manipulating segments from a mesh with billions of segments this check can start to annoy users that want the most extreme performance.

**Comment by serenity4** [comment]
> I just wonder why people consistently try to construct Segment with more than 2 points...

Well, any code that is produced is bound to be used in ways we don't expect. Mostly due to typos/silly errors, but maybe due to misconceptions or another failure somewhere else.

> I think the problem is that the user doesn't have control of this. When we are taking views of the global vector of points in a unstructured mesh, these views won't be static.

At least, views of static arrays won't be affected. For views of dynamic arrays, yes, that's why we need to investigate the cost. But there again, it is pretty easy to produce silent bugs, e.g. you construct your segment with index variables `i:j` with `i` and `j` representing a range with less or more than two elements.

> If, however, people are manipulating segments from a mesh with billions of segments this check can start to annoy users that want the most extreme performance.

Note that we are talking about construction time. Would it really be a big deal? The manipulation of segments would probably be much more expensive in itself. I strongly agree with the saying `premature optimization is the root of all evil".

We can simply add the check for static vectors and `Vector`s to start with. We could also throw an error if the user tries to build a segment from a `Vector` (because it also may get extended over time), but I'm not a fan of this.
