### ISSUE TITLE
Define neighborhoods from primitives

### ISSUE THREAD

**Issue by serenity4** [JuliaGeometry/Meshes.jl#95]
I saw that there are two neighborhood types defined: `Ellipsoid` and `NormBall`. I think it would make more sense to derive neighborhoods directly from a distance function defined on geometrical objects dependent on a metric.

`NormBall` is defined from a metric and a radius. Instead, we could use the functionality it offers directly from a `Sphere` and a `metric`.
`Ellipsoid` is in fact a rotated ellipsoid embedding rotation parameters inside its type. Perhaps we should just define the `Ellipsoid` as a primitive, and define the neighborhood from a rotation, the ellipsoid primitive, and a metric?

That way, we don't have to define special "primitive" types related to neighborhoods, and we can have the `Ellipsoid` directly as a primitive. Instead of these special types, if proper types are needed for dispatch, then a `Neighborhood{P<:Primitive, M}` (`M` being the metric) can be defined instead.

**Comment by juliohm** [comment]
There is a difference between the concept of neighborhood and the concept of simple geometries like balls and ellipsoids. A neighborhood is not attached to any specific location and is free to move around, whereas a geometry is georeferenced to a specific location (e.g. sphere center). We use this difference in GeoStats.jl in order to write algorithms with a moving neighborhood. Please let me know if there is something else that I am missing. We can close the issue otherwise.

**Comment by serenity4** [comment]
The problem is that I'd like an `Ellipsoid` as a primitive too. Without specifying a rotation. The difference you point out (one is defined at a point in space, one only at the origin) stems from embedding the location inside the primitive itself. I'll have to think more about this, but it would be nice to differentiate between geometry and translated geometry. Else we'll have more duplication pop up over time.

EDIT: when I say differentiate, it's about not duplicating them, and use the fact that one is a slightly modified version of the other.
